### ISSUE TITLE
ajouter le nœux de tisserand aux extractions :)

### ISSUE THREAD

**Issue by ixeft** [outilssgdf/outilssgdf#13]
Bonjour,

J’utilise l’extracteur d’outilsgdf en ligne de commande, malheureusement il me manque le nœud de tisserand, serait-il possible de l’ajouter ?

**Comment by sbouchex** [comment]
Bonne idée !

**Comment by sbouchex** [comment]
Par contre, dans l'intranet, peu sont effectivement renseignés : Pour "Paris Sud", uniquement un seul sur 275 responsables

**Comment by ixeft** [comment]
une 20aine, pour paris Céleste, mais principalement en équipe terr, en vérité... Un peu de travail de pédagogie de ce côté là :)
